python train.py \
    --train_dir data/train \
    --test_dir data/test \
    --val_dir data/val \
    --model timm/seresnextaa101d_32x8d.sw_in12k_ft_in1k_288 \
    --head Transformer \
    --rs Random_Resized \
    --aug \
    --bz 32 \
    --lr 0.0001 \
    --epochs 50 \
    --save_dir experiments/experimenet_result